---
name: "Lint"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: "Lint Everything"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "bewuethr/yamllint-action@v1.2.2"
        with:
          config-file: ".yamllint"
      - uses: "pnpm/action-setup@v3"
        with:
          version: 8
      - name: "Export pnpm store"
        shell: "bash"
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: "Setup pnpm cache"
        uses: "actions/cache@v4"
        with:
          path: "${{ env.STORE_PATH }}"
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: "${{ runner.os }}-pnpm-store-"
      - name: "Install dependencies"
        shell: "bash"
        run: "pnpm install"
      - name: "Lint"
        shell: "bash"
        run: "pnpm run lint"
