---
name: "Lint"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: "Lint Everything"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "bewuethr/yamllint-action@v1.2.2"
        with:
          config-file: ".yamllint"
      - uses: "nosborn/github-action-markdown-cli@v2.0.0"
        with:
          files: "."
          config_file: ".markdownlint.yaml"
